Updated copyright year for the ebooks
dotnet-architecture/eBooks pull request #148
Opened 2022-01-11 12:40 UTC by VaishaliRaval

Updated copyright year for the following eBooks

1. architecting-modern-web-apps-azure
2. blazor-for-web-forms-developers
3. cloud-native
4. containerized-lifecycle
5. dapr-for-net-developers
6. devops-aspnet-core
7. grpc-for-wcf-developers
8. microservices
9. modernize-desktop-apps
10. modernize-with-azure-containers
11. porting-existing-aspnet-apps

2022-01-12 07:59 UTC, erjain requested changes
"porting-ebook" file is pushed with a different name and it resulted in 2 files under porting-existing-aspnet-apps, it should be "Porting-Existing-ASP.NET-Apps-to-.NET-Core".

2022-01-13 06:05 UTC, VaishaliRaval commented
I have renamed the porting ebook as Porting-Existing-ASP.NET-Apps-to-.NET-Core

2022-01-13 12:28 UTC, erjain approved these changes

2022-01-13 12:28 UTC, erjain commented
All files are reviewed for copyright 2022.

2022-01-13 12:35 UTC, merged